return {
    {
        "sphamba/smear-cursor.nvim",
        opts = {
            enabled = true,
            smear_insert_mode = true,
            smear_replace_mode = false,
            smear_terminal_mode = false,
            smear_between_buffers = false,
            smear_between_neighbor_lines = true,
            smear_horizontally = true,
            smear_vertically = true,
            smear_diagonally = true,
            smear_to_cmd = true,
            legacy_computing_symbols_support_vertical_bars = false,
            use_diagonal_blocks = true,
            vertical_bar_cursor = false,
            vertical_bar_cursor_insert_mode = true,
            horizontal_bar_cursor_replace_mode = true,
            never_draw_over_target = false,
            hide_target_hack = false,
            scroll_buffer_space = false,
            legacy_computing_symbols_support = true,
            stiffness = 0.9,
            trailing_stiffness = 0.8,
            distance_stop_animating = 0.3,
        },
    },
}
